version: '3.8'

services:
  app:
    image: 'online_shop:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - SPRING_APPLICATION_JSON=$SPRING_JSON
    stdin_open: true
    tty: true

  postgres:
    image: 'postgres:15.2'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=paikeee
      - POSTGRES_DB=shop_db